name: Lint

on: pull_request

jobs:
    build-charm:
        name: "Build the charms"        
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: "Install charmcraft"
              run: |
                  sudo snap install charmcraft --channel=latest/stable --classic            
            - name: "Configure lxd"
              run: |
                  sudo adduser $USER lxd
                  newgrp lxd        
                  #sudo lxd init --auto
                  sudo lxd init --minimal
                  sudo lxc network set lxdbr0 ipv6.address none        
                  sudo chmod a+wr /var/snap/lxd/common/lxd/unix.socket
                  lxc launch ubuntu:22.04
            - name: "Build the charms"
              shell: bash
              run: |
                  echo "test" > version
                  charmcraft clean
                  charmcraft pack

                  echo "charm version: $(cat version)"
