name: Lint

on: pull_request

jobs:
    build-charm:
        name: "Build the charms"        
        runs-on: "ubuntu-latest"
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - name: "Install charmcraft"
              run: |
                  sudo snap install charmcraft --channel=latest/stable --classic            
            - name: "Configure lxd"
              run: |
                  sudo groupadd --force --system lxd
                  sudo usermod --append --groups lxd $USER
                  newgrp lxd
                  sudo snap start lxd
                  sudo lxd waitready --timeout=30
                  sudo lxd init --auto
            - name: "Build the charms"
              shell: bash
              run: |
                  echo "test" > version
                  charmcraft clean
                  charmcraft pack

                  echo "charm version: $(cat version)"
