name: Lint

on: pull_request

jobs:
    build-charm:
        name: "Build the charms"        
        runs-on: "ubuntu-22.04"
        steps:
            - uses: actions/checkout@v3
            - name: Setup operator environment
              uses: charmed-kubernetes/actions-operator@main
              with:
                provider: lxd
                juju-channel: 3.1/stable
            - name: "Build the charms"
              shell: bash
              run: |                  
                  echo "test" > version
                  charmcraft clean
                  charmcraft pack

                  echo "charm version: $(cat version)"
